# Generated by Django 3.2.18 on 2026-05-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_motm', '0005_auto_20260523_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_original',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
