# Generated by Django 3.2.18 on 2026-06-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmt_motm', '0007_alter_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
